RobertoGarcia/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('apps.BlogContent.urls', namespace='Blog')),
    url(r'^', include('apps.Home.urls', namespace='Home')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/BlogContent/urls.py
from django.conf.urls import url, include
from apps.BlogContent.views import SeeBP

urlpatterns = [
    url(r'^MyBlogs', SeeBP.as_view() , name='see_BP'),
]

apps/Home/urls.py
from django.conf.urls import url, include
from apps.Home.views import HomeScreen, AboutMe, Academic

urlpatterns = [
    url(r'^$', HomeScreen, name='HomeScreen'),
    url(r'^AboutMe$', AboutMe, name='AboutMe'),
    url(r'^Academic$', Academic, name='Academic'),
]

apps/BlogContent/models.py
from django.db import models
from datetime import datetime 

#Needed to install pillow for the ImageField

# Create your models here.
class BlogPost(models.Model):
	title=models.CharField(max_length=50)
	content1=models.TextField()
	image1=models.ImageField(upload_to='Blog_Images', blank=True)
	content2=models.TextField(blank=True, null=True)
	image2=models.ImageField(upload_to='Blog_Images', blank=True)
	ref_code=models.TextField(blank=True, null=True)
	github_link=models.TextField(blank=True, null=True)
	references=models.TextField(blank=True, null=True)
	upload_date=models.DateTimeField(auto_now_add=True, blank=True)

	def __str__(self):
		return self.title
#bold stuff in css font-weight: bold;

apps/Home/models.py
from django.db import models

# Create your models here.

apps/BlogContent/forms.py
from django import forms
from apps.BlogContent.models import BlogPost

class BlogForm(forms.ModelForm):
	class Meta:
		model = BlogPost

		fields = [
		'title',
		'content1',
		'content2',
		'ref_code',
		'github_link',
		'references',
		]

		labels = {
		'title': "Title of your post",
		'content1': "Main content",
		'content2': "Additional Content",
		'ref_code': "Reference Code",
		'github_link': "Github Link",
		'references': "References",
		}

		widgets = {
		'title': forms.TextInput(attrs={'class':'form-control'}),
		'content1': forms.TextInput(attrs={'class':'form-control'}),
		'content2': forms.TextInput(attrs={'class':'form-control'}),
		'ref_code': forms.TextInput(attrs={'class':'form-control'}),
		'github_link': forms.TextInput(attrs={'class':'form-control'}),
		'references': forms.TextInput(attrs={'class':'form-control'}),
		}

apps/BlogContent/views.py
from django.shortcuts import render
from django.views.generic import CreateView, ListView
from apps.BlogContent.models import BlogPost
from apps.BlogContent.forms import BlogForm

# Create your views here.

class SeeBP(ListView):
	model = BlogPost
	template_name ='blog/blog.html'
	paginate_by = 3
	ordering = ['-upload_date']
	

apps/Home/views.py
from django.shortcuts import render, render_to_response

# Create your views here.

def HomeScreen(request):
	return render_to_response('index.html')

def AboutMe(request):
	return render_to_response('aboutme/aboutme.html')

def Academic(request):
	return render_to_response('academic/academic.html')

templates/aboutme/aboutme.html
{% extends 'base/base2.html' %}

{% block contenido %}

<div id="aboutme_container">
<h4>AboutMe</h4>
<a href="https://github.com/Roberto09" id ="BTN1-Git" class="btn btn-primary" >Github Profile</a>
<a href="mailto:roberto.gt1509@gmail.com" id ="BTN1-Git" class="btn btn-primary" >Email Me</a>
<a href="https://www.linkedin.com/in/robertog1509/" id ="BTN1-Git" class="btn btn-primary" >Linkedin Profile</a>


<div id="Head-AM">
	<div id="header-AM">
	<h5>Personal Info: </h5>
	</div>

	<p id ="Head-AM-P1">My full name is Roberto Garcia Torres and I am from Monterrey Mexico. At this moment I'am studying a major´s degree in engineering in computer science in the Tecnologico de Monterrey; beofre this I studied Junior-High in Universidad TecMilenio. Personally I’am deeply interested in competitive programming, web and mobile development. This page, in fact is built in Django framework using python. Other things you may want to know about me is that I really like sports, hanging out with my friends and food. I always want to seek discomfort and that is what encourages me to do a lot of things. Here´s a picture of me:
	</p>
	{% load static %} 
	<img id="Profile_Pic" src="{% static 'html_images/Profile.jpeg' %}" alt="Profile Picture">

</div>

<div id="Middle-AM">

	<div id="middle-header-AM">
	<h5>Hobbies:</h5>
	</div>

	<img id="Mountain_Pic" src="{% static 'html_images/Escritorio.jpeg' %}" alt="Profile Picture">


	<p id ="Middle-AM-P1">
<strong>Cultural:</strong><br/>
•	<a href="https://www.rubiks.com/">Rubik´s Cube</a><br/>
•	<a href="https://www.topcoder.com/community/competitive-programming/">Competitive Programming</a><br/>
•	<a href="http://www.selfdirectedlearning.org/what-is-self-directed-learning">Self Learning</a><br/>
<br/>
<strong>Excercise/Sports:</strong><br/>
•	<a href="http://allfitnessgym.com/plaza-tec/">Gym</a><br/>
•	<a href="http://www.historyofsoccer.info/">Soccer</a><br/>

	</p>

</div>


<div id="Foot-AM">

	<div id="foot-header-AM">
	<h5>Awards and Leadership: </h5>
	</div>

	<p id ="Foot-AM-P1">
•	3rd place in TopTeen (1 semester programming competition in college with participants from the 3 CS majors) -2017.<br/>
•	Collaboration as staff in Hack-Mty -2017.<br/>
•	Capitan from my student society in High-School leading about 75 people -2017.<br/>
•	Invitation and assistance to ENLA (National Meeting of Leaders in Action) in Queretaro -2016.<br/>
•	Invitation and assistance to SE-LIDER (national leadership congress) in Monterrey -2015.<br/>

	</p>
	<img id="Profile_Pic" src="{% static 'html_images/Cerro.jpg' %}" alt="Profile Picture">

</div>


<div id="LifePlan">

	<div id="LifePlan-header-AM">
	<h5>Life Plan:</h5>
	</div>

	<p id ="LifePlan-P1">
		During my major as a CS student I would like to be able to work and find as much experience as possible through internships/courses/extracurricular activities. That is because I want to leave college with the highest experience possible. After graduating I would like to work for 3-5 years in a huge company such as google, Facebook, Twitter, Uber, Microsoft, etc. or in a very cool startup. Then, after acquiring some laboral experience, I would like to make my own startup with my team. After that sky is the limit.
	</p>

</div>


<div id="Middle-AM" class="lastC">

	<div id="middle-header-AM">
	<h5>My Ethics Code:</h5>
	</div>

	<img id="Mountain_Pic" src="{% static 'html_images/Mountain.jpeg' %}" alt="Profile Picture">


	<p id ="Middle-AM-P1">
•	Contribuir a la sociedad y al bienestar humano<br>
•	Evitar causar daño a los demás<br>
•	Ser honesto y digno de confiar<br>
•	Ser justo<br>
•	Honrar los derechos de propiedad<br>
•	Dar créditos propios por la propiedad intelectual<br>
•	Respetar la propiedad de otros<br>
•	Honrar la confidencialidad<br>

	</p>

</div>




</div>

{% endblock %}

templates/academic/academic.html
{% extends 'base/base2.html' %}

{% block contenido %}

<div id="aboutme_container">
<h4>Academic</h4>
<a href="https://github.com/Roberto09" id ="BTN1-Git" class="btn btn-primary" >Github Profile</a>
<a href="mailto:roberto.gt1509@gmail.com" id ="BTN1-Git" class="btn btn-primary" >Email Me</a>
<a href="https://www.linkedin.com/in/robertog1509/" id ="BTN1-Git" class="btn btn-primary" >Linkedin Profile</a>

<div id="Head-AM">
	<div id="header-AM">
	<h5>School and Major: </h5>
	</div>

	<p id ="Head-AM-P1">I am studying a major in Engineering in Computer Science in the “Tecnologico de Monterrey”.  This major consists in software development and computer science combined with the skills of a regular engineer. Right now, I am in the 1st semester from the major, which lasts 9 semesters. Regardless of this I seek to learn as much as possible by my own. I would like to include that the main reason why I am studying this is because I believe in the power of the computers combined with your own software and how this allows us to create huge things with the lowest amount of resources.
	</p>
	{% load static %} 
	<img id="Profile_Pic" src="{% static 'html_images/Tec.png' %}" alt="Profile Picture">

</div>

<div id="Middle-AM">

	<div id="middle-header-AM">
	<h5>Technical Skills: </h5>
	</div>

	<img id="Mountain_Pic" src="{% static 'html_images/languages.png' %}" alt="Profile Picture">


	<p id ="Middle-AM-P1">
<strong>Programming Languages:</strong><br/>
•	Python: (Beginner)<br/>
•	C++: (Beginner)<br/>
•	JavaScript: (Beginner)<br/>
<br/>
<strong>Technologies/frameworks:</strong><br/>
•	Django:(Beginner)<br/>
•	Html & Css: (Beginner)<br/>
•	Android Studio (Beginner)<br/>

	</p>

</div>


<div id="Foot-AM" class="lastC">

	<div id="foot-header-AM">
	<h5>My plans for the semesters (They may change with the time):</h5>
	</div>

	<p id ="Foot-AM-P1">
•	1st: Network a lot with my new classmates, learn data bases and begin with android dev.<br>
•	2nd: Start working and learn about machine learning.<br>
•	3rd: Continue working and acquire more knowledge on db and apply for internships.<br>
•	4th: Apply with a party to the Students Society and make a cool team to start building projects.<br>
•	5ht: Start my own startup.<br>
•	6th: Continue working on my startup and start to learn about complex data science.<br>
•	7th: Aim to find a cool job in a huge business.<br>
•	8th: Get deeper into learning UX design and start seeing job opportunities.<br>
•	9th: Make as much experience as possible and find an opportunity to work in a cool company, continue my startup or start a new one.<br>


	</p>
	{% load static %} 
	<img id="Semester_Plans" src="{% static 'html_images/flag.jpg' %}" alt="Profile Picture">




</div>

</div>

{% endblock %}

templates/base/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width; initial-scale=1.0">
  <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'css/custom.css' %}">
  <script type="text/javascript" src="https://code.jquery.com/jquery-1.10.2.min.js"></script>
  <script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
  <script type="text/javascript" src="{% static 'js/custom.js' %}"></script>

  {% block title %} <title>Roberto´s Blog</title> {% endblock %}
</head>
<body id="body-base">

<div class="container">
  {% block navbar %}
        <nav>
            <div class="logo-section">
                <a href="{% url 'Home:HomeScreen' %}"class="logo">ROBERTO´S BLOG</a>
                <button class="hb-button"><i class="fa fa-bars"></i></button>
            </div>
            <ul>
                <li id="menu-movil"><a href="{% url 'Home:Academic' %}">Academic</a></li>
                <li id="menu-movil"><a href="{% url 'Home:AboutMe' %}">About Me</a></li>
                <li id="menu-movil"><a href="{% url 'Blog:see_BP' %}">Blogs & Projects</a></li>

            </ul>
        </nav>




  {% endblock %}

</div>
<div class="rest-body-container">
  {% block contenido %}
  <h5>Este es el blocque del contenido del archivo base</h3>
  {% endblock %}
</div>


  
</body>
</html>

templates/base/base2.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width; initial-scale=1.0">
  <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'css/custom.css' %}">
  <script type="text/javascript" src="https://code.jquery.com/jquery-1.10.2.min.js"></script>
  <script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
  <script type="text/javascript" src="{% static 'js/custom.js' %}"></script>

  {% block title %} <title>Roberto´s Blog</title> {% endblock %}
</head>
<body id = "body-base2">

<div class="container">
  {% block navbar %}
        <nav>
            <div class="logo-section">
                <a href="{% url 'Home:HomeScreen' %}"class="logo">ROBERTO´S BLOG</a>
                <button class="hb-button"><i class="fa fa-bars"></i></button>
            </div>
            <ul>
                <li id="menu-movil"><a href="{% url 'Home:Academic' %}">Academic</a></li>
                <li id="menu-movil"><a href="{% url 'Home:AboutMe' %}">About Me</a></li>
                <li id="menu-movil"><a href="{% url 'Blog:see_BP' %}">Blogs & Projects</a></li>
            </ul>
        </nav>




  {% endblock %}

</div>
<div class="rest-body-container">
  {% block contenido %}
  <h5>Este es el blocque del contenido del archivo base</h3>
  {% endblock %}
</div>


  
</body>
</html>

templates/blog/blog.html
{% extends 'base/base2.html' %}
{% block contenido %}


	<div id="All_Blog_Content">

<div id="Blog_Part">
<div id="Blog_Header">
<h2 id="header-MB">My Blogs</h2>
<p id="header-description-MB">In this section I post blogs on updates of cool stuff I am working on or small articles about my CS experiences.</p>
</div>

{% if object_list %}
	{% for BP in object_list %}
	<div id="Blog_Container">


	<h3 id="Post_Title" >{{BP.title}}</h3>
	<p>{{BP.content1}}</p>

	{% if BP.image1 %}
	<img class= "BP_image"src="{{ BP.image1.url }}" alt="">
	{% endif %}

	{% if BP.content2 %}
	<p>{{BP.content2}}</p>
	{% endif %}

	{% if BP.image2 %}
	<img class= "BP_image" src="{{ BP.image2.url }}" alt="">
	{% endif %}

	{% if BP.ref_code %}

	<p id = "Ref_Code">Codigo de referencia: <br> {{BP.ref_code|linebreaks}}</p>
	{% endif %}


	{% if BP.github_link %}
	<p>GitHub link: {{BP.github_link}}</p>
	{% endif %}

	{% if BP.references %}
	<p>Referencias: {{BP.references}}</p>
	{% endif %}


	<p id= "Blog_Date">Posted on: {{BP.upload_date}} by Roberto Garcia</p>
	</div>
	{% endfor %}
{% endif %}


<div id="Botones_Blog">
	{% if page_obj.has_previous %}
	<a href="?page={{ page_obj.previous_page_number }}" class="btn btn-primary" >Previous Page</a>
	{% endif %}

	{% if page_obj.has_next %}
	<a href="?page={{ page_obj.next_page_number }}" class="btn btn-primary" >Next Page</a>
	{% endif %}

</div>




</div>

<div id="Lastest_Blogs">
	<h4>Page({{page_obj.number}}).Blogs in this page:</h4>
	{% for BPLB in object_list %}
	<p id ="preview_title">Titulo: {{BPLB.title}}</p>
	<p id="preview_content">{{BPLB.content1|slice:":200"}}...</p>

	{% if BPLB.image1 %}
	<img id ="preview_image" src="{{ BPLB.image1.url }}" alt="">
	{% endif %}

	{% endfor %}


</div>

	</div>



{% endblock %}

templates/index.html
{% extends 'base/base.html' %}
{% block contenido %}
<div id = "index_container">
<h3>Welcome to Roberto´s Blog</h3>


<div id="intro_p">
<p>Hi there! this is a blog mainly about my personal proyects. However I also include other stuff like what am I learning and sometimes personal experiences regarding IT. I really hope you find it interesting sweeping through my posts. If you have any recomendation or construtive criticism feel free to email me at 
<a href = 'mailto:roberto.gt1509@gmail.com'>roberto.gt1509@gmail.com</a>
</p>


</div>


<div id="Buttons">

<a href="https://github.com/Roberto09" id ="BTN1-Git" class="btn btn-primary" >Github</a>

<a href="{% url 'Home:AboutMe' %}" id ="BTN2" class="btn btn-primary">AboutMe</a>

<a href="{% url 'Blog:see_BP' %}" id ="BTN1" class="btn btn-primary">Blogs & Projects
</a>

<a href="{% url 'Home:Academic' %}" id ="BTN2" class="btn btn-primary">Academic</a>

<a href="https://www.linkedin.com/in/robertog1509/" id ="BTN1-Git" class="btn btn-primary" >Linkedin</a>

</div>


</div>




{% endblock %}